In [ ]:
import pandas as pd

data_1=['junior','sub junior','senior','junior','senior','sub junior','junior','senior','junior','junior','sub junior','senior','junior','senior','sub junior','junior','senior','junior']
data_2=['senior','sub junior','junior','junior','sub junior','senior','junior','senior','senior','sub junior','senior','sub junior','junior','junior','sub junior','senior','junior','senior','senior','sub junior']
data=pd.Series(data_1)
print(data)
data.value_counts()

0         junior
1     sub junior
2         senior
3         junior
4         senior
5     sub junior
6         junior
7         senior
8         junior
9         junior
10    sub junior
11        senior
12        junior
13        senior
14    sub junior
15        junior
16        senior
17        junior
dtype: object


junior        8
senior        6
sub junior    4
Name: count, dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd

label_encoder = LabelEncoder()


encoded_data = label_encoder.fit_transform(data)

print("Original Data:")
print(data)
print("\nEncoded Data:")
print(encoded_data)

print("\nClasses and their encoded values:")
for i, label in enumerate(label_encoder.classes_):
    print(f"{label}: {i}")

Original Data:
0         junior
1     sub junior
2         senior
3         junior
4         senior
5     sub junior
6         junior
7         senior
8         junior
9         junior
10    sub junior
11        senior
12        junior
13        senior
14    sub junior
15        junior
16        senior
17        junior
dtype: object

Encoded Data:
[0 2 1 0 1 2 0 1 0 0 2 1 0 1 2 0 1 0]

Classes and their encoded values:
junior: 0
senior: 1
sub junior: 2


In [ ]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

one_hot_encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)


data_reshaped = data.values.reshape(-1, 1)

one_hot_encoded_data = one_hot_encoder.fit_transform(data_reshaped)

print("Original Data (first 5 entries):")
print(data.head())
print("\nOne-Hot Encoded Data (first 5 entries):")

print(one_hot_encoded_data[:5])

print("\nFeature names (categories) in order of columns:")
print(one_hot_encoder.get_feature_names_out(['category']))


one_hot_df = pd.DataFrame(one_hot_encoded_data, columns=one_hot_encoder.get_feature_names_out(['category']))
print("\nOne-Hot Encoded DataFrame (first 5 rows):")
display(one_hot_df.head())

Original Data (first 5 entries):
0        junior
1    sub junior
2        senior
3        junior
4        senior
dtype: object

One-Hot Encoded Data (first 5 entries):
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]

Feature names (categories) in order of columns:
['category_junior' 'category_senior' 'category_sub junior']

One-Hot Encoded DataFrame (first 5 rows):


category_junior  category_senior  category_sub junior
0              1.0              0.0                  0.0
1              0.0              0.0                  1.0
2              0.0              1.0                  0.0
3              1.0              0.0                  0.0
4              0.0              1.0                  0.0

In [ ]:
import pandas as pd
from google.colab import drive
from sklearn.preprocessing import OrdinalEncoder # Changed from LabelEncoder

drive.mount('/content/drive')


path='/content/drive/My Drive/loan_approved.csv'
df=pd.read_csv(path)

print(df.isnull().sum())

numeric_cols = df.select_dtypes(include=['number']).columns
df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].median())

categorical_cols = df.select_dtypes(include=['object']).columns

df[categorical_cols] = df[categorical_cols].fillna(df[categorical_cols].mode().iloc[0])



ordinal_encoder = OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1) # Use -1 for unknown values


encoded_data = ordinal_encoder.fit_transform(df[categorical_cols])

encoded_col_names = [f"{col}_encoded" for col in categorical_cols]


df[encoded_col_names] = encoded_data



encoded_columns = {col: ordinal_encoder.categories_[i] for i, col in enumerate(categorical_cols)}


print("\nDataFrame after filling NaNs and adding encoded columns (first 5 rows):")
display(df.head())
print(df.info())
df.to_csv('/content/drive/My Drive/pre_processesed.csv',index=False)



Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Loan_ID                    0
Gender                    13
Married                    3
Dependents                15
Education                  0
Self_Employed             32
ApplicantIncome            0
CoapplicantIncome          0
LoanAmount                22
Loan_Amount_Term          14
Credit_History            50
Property_Area              0
Loan_Status (Approved)     0
dtype: int64

DataFrame after filling NaNs and adding encoded columns (first 5 rows):


Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  ...  \
0             5849                0.0       128.0             360.0  ...   
1             4583             1508.0       128.0             360.0  ...   
2             3000                0.0        66.0             360.0  ...   
3             2583             2358.0       120.0             360.0  ...   
4             6000                0.0       141.0             360.0  ...   

   Property_Area Loan_Status (Approved) Loan_ID_encoded  Gender_encoded  \
0          Urban                      Y             0.0             1.0   
1          Rural                      N             1.0             1.0   
2          Urban                      Y             2.0             1.0   
3          Urban                      Y             3.0             1.0   
4          Urban                      Y             4.0             1.0   

   Married_encoded  Dependents_encoded  Education_encoded  \
0              0.0                 0.0                0.0   
1              1.0                 1.0                0.0   
2              1.0                 0.0                0.0   
3              1.0                 0.0                1.0   
4              0.0                 0.0                0.0   

   Self_Employed_encoded  Property_Area_encoded  \
0                    0.0                    2.0   
1                    0.0                    0.0   
2                    1.0                    2.0   
3                    0.0                    2.0   
4                    0.0                    2.0   

   Loan_Status (Approved)_encoded  
0                             1.0  
1                             0.0  
2                             1.0  
3                             1.0  
4                             1.0  

[5 rows x 21 columns]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 21 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   Loan_ID                         614 non-null    object 
 1   Gender                          614 non-null    object 
 2   Married                         614 non-null    object 
 3   Dependents                      614 non-null    object 
 4   Education                       614 non-null    object 
 5   Self_Employed                   614 non-null    object 
 6   ApplicantIncome                 614 non-null    int64  
 7   CoapplicantIncome               614 non-null    float64
 8   LoanAmount                      614 non-null    float64
 9   Loan_Amount_Term                614 non-null    float64
 10  Credit_History                  614 non-null    float64
 11  Property_Area                   614 non-null    object 
 12  Loan_Status (Approved)          614 

1.identify the outliers with histogram,boxplot
2.
3. skewness measure

In [ ]:
from sklearn.preprocessing import PowerTransformer
import pandas as pd
import numpy as np
trans=PowerTransformer(method='yeo-johnson')
la_trans=trans.fit_transform(df[['CoapplicantIncome']]) # Corrected 'data' to 'df'
la_trans.shape
print("skewness :",pd.Series(la_trans.reshape(614,)).skew())
print("Kurtosis",pd.Series(la_trans.reshape(614,)).kurtosis())
np.log(df['LoanAmount']) # Changed 'data' to 'df' to access the correct DataFrame

skewness : -0.14564645710551902
Kurtosis -1.8778432766544493


0      4.852030
1      4.852030
2      4.189655
3      4.787492
4      4.948760
         ...   
609    4.262680
610    3.688879
611    5.533389
612    5.231109
613    4.890349
Name: LoanAmount, Length: 614, dtype: float64