In [ ]:
import numpy as np
arr1=np.array([1,2,3])
print(arr1)
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)
print(arr2.ndim)
arr3=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr3)
print(arr3.ndim)


[1 2 3]
[[1 2 3]
 [4 5 6]]
2
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


In [ ]:
zeros=np.zeros((2,3))
ones=np.ones((2,3))
print(zeros)
print(ones)
random_val=np.random.random((3,3))
print(random_val)
identity=np.eye(3)
print(identity)
range_arr=np.arange(0,10,2)
print(range_arr)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0.42231595 0.89040246 0.73321745]
 [0.80603522 0.54735659 0.58173508]
 [0.29973273 0.92064745 0.99069724]]


In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print("Shape:",arr.shape)
print("Size:",arr.size)
print("Data type:",arr.dtype)
print("Number of dimensions: ",arr.ndim)

Shape: (2, 3)
Size: 6
Data type: int64
Number of dimensions:  2


You are working as a Data Engineer for a smart agriculture startup that collects sensor data from multiple greenhouses. Each greenhouse has sensors that record temperature (°C) readings at different times of the day. You received the following data: Your tasks are: Create NumPy arrays Create a 2D NumPy array named temp_data to represent the temperature readings from both greenhouses. Print the array. Check array properties Print the shape, size, data type, and number of dimensions of temp_data. Add a third greenhouse The third greenhouse (GH3) records [21, 23, 22]. Create a new array updated_temp_data that includes all three greenhouses. Generate supporting data Create a zeros array (2×3) called sensor_error_flags to represent whether there were any sensor errors (0 means no error). Create an identity matrix of size 3×3 named greenhouse_identity to uniquely identify each greenhouse. Display all arrays Print updated_temp_data, sensor_error_flags, and greenhouse_identity.

In [ ]:
gh1=np.array([22,25,20])
gh2=np.array([21,23,22])
temp_data=np.array([gh1,gh2])
print(temp_data)
arr=temp_data
print("Shape:",arr.shape)
print("Size:",arr.size)
print("Data type:",arr.dtype)
print("Number of dimensions: ",arr.ndim)
# Reshape the 1D array to a 2D array with the same number of rows as temp_data
gh3=np.array([21,23,22])
updated_temp_data = np.array([gh1,gh2,gh3])
sensor_error_flags=np.zeros((2,3))
greenhouse_identity=np.eye(3)
print(updated_temp_data)
print(sensor_error_flags)
print(greenhouse_identity)

[[22 25 20]
 [21 23 22]]
Shape: (2, 3)
Size: 6
Data type: int64
Number of dimensions:  2
[[22 25 20]
 [21 23 22]
 [21 23 22]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
arr=np.array([[10,20,30],[40,50,60]])
print(arr[0,1])
print(arr[1,-1])
print(arr[:,1:])

20
60
[[20 30]
 [50 60]]


In [ ]:
Apples=np.array([50,60,55,70,65,80,90])
Oranges=np.array([40,45,50,60,55,70,75])

shipments=np.array([Apples,Oranges])
print(shipments[0,2])
print(shipments[1,-1])
print(shipments[:, 0:5])
print(shipments[:, 5:7])
print(shipments[0,2:6])
shipments[0,-2]=100
print(shipments)


55
75
[[50 60 55 70 65]
 [40 45 50 60 55]]
[[80 90]
 [70 75]]
[55 70 65 80]
[[ 50  60  55  70  65 100  90]
 [ 40  45  50  60  55  70  75]]


You are working as a Data Analyst at a fruit distribution company.
The company stores the number of fruit boxes shipped per day (for 1 week) in a 2D NumPy array where:
Each row represents a type of fruit.
Each column represents a day of the week (Mon–Sun).


Your Tasks
Create the 2D NumPy array
Create an array named shipments using the above data.
Access single elements (Indexing):
Get the number of Apples shipped on Wednesday.
Get the number of Oranges shipped on Sunday.
Access multiple elements (Slicing):
Extract all the weekday shipments (Mon–Fri) for all fruits.
Extract only the weekend shipments (Sat & Sun).
Extract the shipments of Apples from Wednesday to Saturday.
Bonus (Practice thinking):
Replace the Saturday shipment of Apples (currently 80) with 100 using indexing.

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])

#universal functions
arr=np.array([1,2,3])
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.power(a,b))
print(np.mod(a,b))
print(np.exp(arr))
print(np.sqrt(arr))
print(np.log(arr))
print(np.expm1(arr))
print(np.mean(arr))
print(np.sum(arr))
print(np.max(arr))
print(np.min(arr))
print(np.std(arr))
print(np.var(arr))
print(np.logical_and(a,b))
print(np.logical_or(a,b))
print(np.logical_not(a))
print(np.logical_xor(a,b))
np.greater(a,b)
np.less(a,b)
np.equal(a,b)
np.not_equal(a,b)
np.greater_equal(a,b)
np.less_equal(a,b)
np.bitwise_and(a,b)
np.bitwise_or(a,b)
np.bitwise_xor(a,b)
np.invert(a)
np.sin(arr)
np.cos(arr)
np.tan(arr)

np.degrees(arr)
np.radians(arr)
np.round(arr)
np.floor(arr)
np.ceil(arr)
np.trunc(arr)

[[ 8 10 12]
 [14 16 18]]
[[-6 -6 -6]
 [-6 -6 -6]]
[[ 7 16 27]
 [40 55 72]]
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]
[[         1        256      19683]
 [   1048576   48828125 2176782336]]
[[1 2 3]
 [4 5 6]]
[ 2.71828183  7.3890561  20.08553692]
[1.         1.41421356 1.73205081]
[0.         0.69314718 1.09861229]
[ 1.71828183  6.3890561  19.08553692]
2.0
6
3
1
0.816496580927726
0.6666666666666666
[[ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]]
[[False False False]
 [False False False]]
[[False False False]
 [False False False]]


array([1., 2., 3.])

1. Arithmetic ufuncs
Operate element-wise on arrays.
np.add(x, y)
np.subtract(x, y)
np.multiply(x, y)
np.divide(x, y)
np.power(x, y)
np.mod(x, y)
🔹 2. Exponential and Logarithmic ufuncs
(You already covered these)
np.exp(x)
np.log(x)
np.log10(x)
np.log2(x)
np.expm1(x)    # exp(x) - 1
🔹 3. Trigonometric ufuncs
np.sin(x)
np.cos(x)
np.tan(x)
np.arcsin(x)
np.arccos(x)
np.arctan(x)
np.degrees(x)
np.radians(x)
🔹 4. Rounding ufuncs
np.round(x)
np.floor(x)
np.ceil(x)
np.trunc(x)
🔹 5. Statistical ufuncs
(Operate along an axis or entire array)
np.min(x)
np.max(x)
np.mean(x)
np.std(x)
np.var(x)
np.sum(x)
np.prod(x)
🔹 6. Logical ufuncs
np.logical_and(x, y)
np.logical_or(x, y)
np.logical_not(x)
np.logical_xor(x, y)
🔹 7. Comparison ufuncs
(Return Boolean arrays)
np.greater(x, y)
np.less(x, y)
np.equal(x, y)
np.not_equal(x, y)
np.greater_equal(x, y)
np.less_equal(x, y)
🔹 8. Bitwise ufuncs
(Operate on integers)
np.bitwise_and(x, y)
np.bitwise_or(x, y)
np.bitwise_xor(x, y)
np.invert(x)


In [ ]:
farmA=np.array([[10,12,11],[9,11,10],[12,13,14],[8,7,9]])
farmB=np.array([[20,19,21],[18,20,19],[22,23,21],[17,18,16]])
farmC=np.array([[15,16,14],[14,13,15],[16,17,18],[12,11,13]])
production_all=np.array([farmA,farmB,farmC])

# Change the dtype to float to allow adding float values
production_all = production_all.astype(np.float64)


arr=production_all
print("Shape:",arr.shape)
print("Size:",arr.size)
print("Data type:",arr.dtype)
print("Number of dimensions: ",arr.ndim)

# Calculate total energy production per farm
total_per_farm = np.sum(production_all, axis=(1, 2))
print("\nTotal energy production per farm:")
print(total_per_farm)

# Calculate mean, std, and var per farm (along axes 1 and 2)
mean_per_farm=np.mean(production_all, axis=(1, 2), keepdims=True)
print("\nMean per farm:")
print(mean_per_farm)
std_per_farm=np.std(production_all, axis=(1, 2), keepdims=True)
print("\nStandard deviation per farm:")
print(std_per_farm)
var_per_farm=np.var(production_all, axis=(1, 2), keepdims=True)
print("\nVariance per farm:")
print(var_per_farm)


hour_weights=np.array([0.5,1.0,0.75])
weighted_per_panel=np.dot(production_all,hour_weights)
print("\nWeighted per panel:")
print(weighted_per_panel)

b=0.5
# Add offset to Farm B data inside production_all using broadcasting
production_all[1] += b
print("\nProduction data with offset added to Farm B:")
print(production_all)


# Z-score normalize each farm's panel-hour readings using per-farm mean and std
# Handle potential division by zero if std is 0
normalized_production = np.where(std_per_farm != 0, (production_all - mean_per_farm) / std_per_farm, 0)
print("\nNormalized production data (z-score per farm):")
print(normalized_production)

# Apply many ufuncs (example - you can add more as needed)
print("\nApplying ufuncs (example np.exp):")
print(np.exp(normalized_production))

# You can add more ufuncs here as per the original task list
print("\nApplying ufuncs (example np.sin):")
print(np.sin(normalized_production))

# Add print statements for the rounding ufuncs as noted previously
print("\nApplying rounding ufuncs (np.floor):")
print(np.floor(production_all)) # This line was missing a print statement
print("\nApplying rounding ufuncs (np.ceil):")
print(np.ceil(production_all)) # This line was missing a print statement
print("\nApplying rounding ufuncs (np.trunc):")
print(np.trunc(production_all)) # This line was missing a print statement


high_output=production_all>20
even_hours_mask=np.array([[True,False,True],[True,False,True],[True,False,True],[True,False,True]])

print("\nLogical AND (high_output and even_hours_mask):")
print(np.logical_and(high_output[0],even_hours_mask)) # Assuming even_hours_mask applies to each farm similarly, demonstrating with farm 0

print("\nLogical OR (high_output and even_hours_mask):")
print(np.logical_or(high_output[0],even_hours_mask)) # Demonstrating with farm 0

print("\nLogical NOT (even_hours_mask):")
print(np.logical_not(even_hours_mask))

print("\nLogical XOR (high_output and even_hours_mask):")
print(np.logical_xor(high_output[0],even_hours_mask)) # Demonstrating with farm 0


print("\nGreater equal (production_all, production_all):")
print(np.greater_equal(production_all,production_all))
print("\nLess (production_all, production_all):")
print(np.less(production_all,production_all))

alerts=np.array([[1,0,1],[0,0,1],[1,1,0],[0,1,0]])

print("\nBitwise AND (alerts, alerts):")
print(np.bitwise_and(alerts,alerts))
print("\nBitwise OR (alerts, alerts):")
print(np.bitwise_or(alerts,alerts))
print("\nBitwise INVERT (alerts):")
print(np.invert(alerts))



print("\nArithmetic ufuncs (example np.add):")
print(np.add(production_all,production_all))
print("\nArithmetic ufuncs (example np.subtract):")
print(np.subtract(production_all,production_all))
print("\nArithmetic ufuncs (example np.multiply):")
print(np.multiply(production_all,production_all))
print("\nArithmetic ufuncs (example np.divide):")
print(np.divide(production_all,production_all))
print("\nArithmetic ufuncs (example np.power):")
print(np.power(production_all,production_all))
print("\nArithmetic ufuncs (example np.mod):")
print(np.mod(production_all,production_all))

print("\nAggregation over ufunc outputs (example np.sum(np.exp(normalized_production))):")
print(np.sum(np.exp(normalized_production)))
print("\nAggregation over ufunc outputs (example np.mean(np.sin(normalized_production))):")
print(np.mean(np.sin(normalized_production)))


# Broadcast-based summary table
print("\nBroadcast-based summary table:")
# Calculate panel totals per farm (sum across hours for each panel)
panel_totals_per_farm = np.sum(production_all, axis=2)
print("Panel totals per farm:")
print(panel_totals_per_farm)

# Compute needs_maintenance (True if any panel in that farm has total < 40)
needs_maintenance = np.any(panel_totals_per_farm < 40, axis=1)
print("Needs maintenance per farm:")
print(needs_maintenance)

# Final KPIs (aggregation)
overall_total=np.sum(production_all)
print("\nOverall total production:")
print(overall_total)

peak_hour_index=np.argmax(production_all)
print("\nIndex of peak hour value (flattened array):")
print(peak_hour_index)
average_per_panel=np.mean(production_all,axis=(1,2))
print("\nAverage per panel across all farms:")
print(average_per_panel)

Shape: (3, 4, 3)
Size: 36
Data type: float64
Number of dimensions:  3

Total energy production per farm:
[126. 234. 174.]

Mean per farm:
[[[10.5]]

 [[19.5]]

 [[14.5]]]

Standard deviation per farm:
[[[1.97905701]]

 [[1.97905701]]

 [[1.97905701]]]

Variance per farm:
[[[3.91666667]]

 [[3.91666667]]

 [[3.91666667]]]

Weighted per panel:
[[25.25 23.   29.5  17.75]
 [44.75 43.25 49.75 38.5 ]
 [34.   31.25 38.5  26.75]]

Production data with offset added to Farm B:
[[[10.  12.  11. ]
  [ 9.  11.  10. ]
  [12.  13.  14. ]
  [ 8.   7.   9. ]]

 [[20.5 19.5 21.5]
  [18.5 20.5 19.5]
  [22.5 23.5 21.5]
  [17.5 18.5 16.5]]

 [[15.  16.  14. ]
  [14.  13.  15. ]
  [16.  17.  18. ]
  [12.  11.  13. ]]]

Normalized production data (z-score per farm):
[[[-0.25264558  0.75793673  0.25264558]
  [-0.75793673  0.25264558 -0.25264558]
  [ 0.75793673  1.26322788  1.76851903]
  [-1.26322788 -1.76851903 -0.75793673]]

 [[ 0.50529115  0.          1.01058231]
  [-0.50529115  0.50529115  0.        ]
  [ 

You are a data engineer at a renewable-energy company that runs 3 solar farms.

Each farm has 4 solar panels, and each panel reports hourly energy production (kWh) for 3 hours during a test window.

Given data (raw)
Create arrays from these values:
production — shape (3 farms × 4 panels × 3 hours) represented as a 2D array per farm (you can stack/create as shown in tasks).
Farm A panels (rows = panels, cols = hours):


Tasks
Create arrays
Create three 2D NumPy arrays farmA, farmB, farmC (each shape (4,3)).
Stack them into a single 3D array production_all of shape (3, 4, 3).
Array attributes
Print the .shape, .size, .dtype, and .ndim of production_all.
Per-farm totals (arithmetic & aggregation)
Use aggregation ufuncs to compute the total energy per farm (sum across panels & hours) → total_per_farm (shape (3,)).
Compute mean, std, and var per farm.
Per-hour matrix multiplication idea (matrix op)
For a quick weighted estimate, create a hour_weights row vector of shape (3,) = [0.5, 1.0, 0.75] (weights for hour1, hour2, hour3).
Compute weighted_per_panel by performing a dot product between each farm's panel-row and hour_weights to get per-panel weighted energy. (Use np.dot / matrix multiplication appropriately.)
Broadcasting adjustments
The operator notices a fixed calibration offset of +0.5 kWh for all panels in Farm B. Use broadcasting to add this offset to Farm B data inside production_all (without recreating whole array manually).
Element-wise arithmetic (ufuncs: add/sub/mul/div/power/mod)
Compute a normalized version where you:
subtract the per-farm mean (use broadcasting),
divide by the per-farm std (broadcasting) — i.e., z-score normalize each farm's panel-hour readings.
Apply many ufuncs (use the ufuncs listed previously)

Apply the following element-wise operations (create variables for each) on the normalized data (or a copy) and show the resulting arrays (or summaries — shape/dtype/first row) where appropriate:
Exponential family: np.exp, np.expm1, np.log (note: handle non-positive inputs if needed), np.log10, np.log2.
Trigonometric: np.sin, np.cos, np.tan, np.arcsin, np.arccos, np.arctan, plus np.degrees, np.radians applied appropriately.
Rounding: np.round, np.floor, np.ceil, np.trunc.
Comparison & logical ufuncs: create a boolean mask high_output = production_all > 20 and apply np.logical_and, np.logical_or, np.logical_not, np.logical_xor combining masks (e.g., high_output and even_hours_mask). Also use comparison ufuncs like np.greater_equal, np.less.
Bitwise ufuncs (on integer arrays): create an integer array alerts = np.array([[1,0,1],[0,0,1],[1,1,0],[0,1,0]]) for each farm (shape match required) — then apply np.bitwise_and, np.bitwise_or, np.invert where sensible.
Arithmetic ufuncs again: np.add, np.subtract, np.multiply, np.divide, np.power, np.mod.
Aggregations over ufunc outputs: e.g., np.sum(np.exp(...)), np.mean(np.sin(...)).
Broadcast-based summary table
Use broadcasting to compute a (3,4) array panel_totals_per_farm = total per panel (sum across hours for each panel), and then compute a (3,) boolean needs_maintenance saying True if any panel in that farm has total < 40. Use np.min, np.max, np.any, np.all.
Final KPIs (aggregation)
Compute:
overall_total (sum of all farms),
peak_hour value (max across hours) and which farm & panel produced it (use np.argmax with careful unraveling),
average_per_panel across all farms.



In [ ]:
a=np.array([1,2])
b=np.array([3,4])
print(np.vstack((a,b)))
print(np.hstack((a,b)))
arr=np.array_split(arr,3)
arr=np.array([1,2,3,4,5])
print(arr[arr>3])
arr=np.array([10,20,30,40])
indices=[0,2]
print(arr[indices])

[[1 2]
 [3 4]]
[1 2 3 4]
[4 5]
[10 30]


In [ ]:
arr=np.array([1,2,3])
view=arr.view()
view[0]=10
print(arr)
copy=arr.copy()
copy[0]=10
print(arr)

[10  2  3]
[10  2  3]


In [ ]:
arr=np.array([1,2,3])
np.save('array.npy',arr)
loaded_arr=np.load('array.npy')
print(loaded_arr)

[1 2 3]


In [ ]:
arr=np.arange(10,50)
a=np.random.randint(0,1,size=(3,3))
arr3=np.array([[[1,2],[4,5]],[[7,8],[10,11]]])
arr4=np.array([[[2,4],[8,10]],[[14,16],[20,22]]])

print("Shape:",arr3.shape)
print("Size:",arr3.size)
print("Data type:",arr3.dtype)
b=5
print(arr3*arr4)
arr=np.arange(1,26)
arr5=np.reshape(arr,(5,5))
print(arr5[0])
print(arr5[:,-1])
print(arr5[0:3,0:2])
c=np.random.randint(10,100,size=10)
print(np.max(c))
print(np.min(c))
print(np.mean(c))
print(np.std(c))
d=np.arange(1,13)
print(np.reshape(d,(3,4)))
e=np.ones((3,3))
f=np.array([1,2,3])
print(e+f)
f=np.random.randint(1,50,size=10)
print(f)
print(f[f%5==0])
print(np.dot(arr3,arr4))
g=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
indices=[0,1,2,3]
print(g[indices,indices])


Shape: (2, 2, 2)
Size: 8
Data type: int64
[[[  2   8]
  [ 32  50]]

 [[ 98 128]
  [200 242]]]
[1 2 3 4 5]
[ 5 10 15 20 25]
[[ 1  2]
 [ 6  7]
 [11 12]]
90
26
55.1
22.55415704476671
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]
[12 38 13  9 28  2  8  6 27 11]
[]
[[[[ 18  24]
   [ 54  60]]

  [[ 48  66]
   [156 174]]]


 [[[ 78 108]
   [258 288]]

  [[108 150]
   [360 402]]]]
[ 1  6 11 16]


TasksArray Creation
Create a 1D array of numbers from 10 to 50.
Create a 3x3 array of random numbers between 0 and 1.
Array Attributes
Find the shape, size, and data type of the array you created in the previous task.
Basic Operations
Add 5 to every element of a 1D array.
Multiply two 2D arrays element-wise.
Indexing and Slicing
Create a 5x5 array of integers from 1 to 25. Extract:
The first row.
The last column.
A subarray of the first three rows and first two columns.
Aggregation
Create a 10-element array of random integers between 10 and 100. Find:
The maximum value.
The minimum value.
The mean and standard deviation.
Reshaping
Convert a 1D array of numbers from 1 to 12 into a 3x4 matrix.
Broadcasting
Create a 3x3 matrix of ones. Add a 1D array [1, 2, 3] to each row.
Filtering
Create a 1D array of random integers between 1 and 50. Extract all elements that are divisible by 5.
Matrix Multiplication
Create two 2x2 matrices and perform matrix multiplication.
Advanced Indexing
Given a 4x4 array, use fancy indexing to extract the diagonal elements.
